defaults: &defaults
  host: localhost
  port: 5672
  exchange_name: "S2.exchange"
  durable: true
  message_persistent: true
  prefetch_number: 1

test:
  <<: *defaults
  exchange_name: "S2.exchange.test"
  durable: false
  message_persistent: false

development:
  <<: *defaults

