defaults: &defaults
  url: "amqp://localhost:5672"
  exchange_name: "S2.exchange"
  durable: true
  message_persistent: true
  prefetch_number: 1
  heart_beat: 0

test:
  <<: *defaults
  exchange_name: "S2.exchange.test"
  durable: false
  message_persistent: false

development:
  <<: *defaults

