defaults: &defaults
  url: "amqp://localhost:5672"
  exchange_name: "S2.exchange"
  durable: true
  message_persistent: true
  prefetch_number: 1
  # You can define a heart_beat value, then the bunny client will use this value.
  # If you do not define the heart_beat value, then the bunny client will use the value provided by the RabbitMQ server.
  #heart_beat: 0

test:
  <<: *defaults
  exchange_name: "S2.exchange.test"
  durable: false
  message_persistent: false

development:
  <<: *defaults

