development_:
  adapter: postgres
  database: core

development:
  adapter: sqlite
  database: dev.db

test:
  adapter: sqlite
  database: test.db

development__:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: development
  username: root
  password:
  socket: /tmp/mysql.sock

test__:
  adapter: mysql2
  encoding: utf8
  charset: utf8
  database: test_lims_api
  username: root
  password:
  socket: /tmp/mysql.sock
